// lib/db/src/schema/sects.ts (Drizzle ORM Schema)
export const DRIZZLE_SECT_SCHEMA_CODE = [
  'import { pgTable, text, integer, bigint, timestamp } from "drizzle-orm/pg-core";',
  'import { createInsertSchema } from "drizzle-zod";',
  'import { z } from "zod/v4";',
  '',
  '// 1. BẢNG TÔNG MÔN (Hỗ trợ Hộ Sơn Trận Pháp, Ngân Khố, PK Points)',
  'export const sectsTable = pgTable("sects", {',
  '  id: bigint("id", { mode: "bigint" }).primaryKey().generatedAlwaysAsIdentity(),',
  '  name: text("name").notNull().unique(),',
  '  leaderDiscordId: text("leader_discord_id").notNull(),',
  '  leaderName: text("leader_name").notNull(),',
  '  level: integer("level").notNull().default(1),',
  '  spiritTreasury: bigint("spirit_treasury", { mode: "bigint" }).notNull().default(0n),',
  '  ',
  '  // Hộ Sơn Trận Pháp (Phòng thủ khi bị tông môn khác PK tập kích)',
  '  formationLevel: integer("formation_level").notNull().default(1),',
  '  formationDurability: integer("formation_durability").notNull().default(5000),',
  '  maxFormationDurability: integer("max_formation_durability").notNull().default(5000),',
  '  ',
  '  // Điểm PK Thế Lực & Thống Kê Chiến Tranh',
  '  pkPoints: integer("pk_points").notNull().default(1000),',
  '  warsWon: integer("wars_won").notNull().default(0),',
  '  warsLost: integer("wars_lost").notNull().default(0),',
  '  warStatus: text("war_status").notNull().default("peace"), // peace | at_war | cooldown',
  '  targetSectId: bigint("target_sect_id", { mode: "bigint" }),',
  '  ',
  '  slogan: text("slogan").default("Nhất đạo thông thiên, vạn cổ trường tồn!"),',
  '  maxMembers: integer("max_members").notNull().default(20),',
  '  createdAt: timestamp("created_at").defaultNow().notNull(),',
  '  updatedAt: timestamp("updated_at").defaultNow().notNull(),',
  '});',
  '',
  '// 2. BẢNG THÀNH VIÊN TÔNG MÔN (Phân Quyền & Điểm Chiến Công)',
  'export const sectMembersTable = pgTable("sect_members", {',
  '  id: bigint("id", { mode: "bigint" }).primaryKey().generatedAlwaysAsIdentity(),',
  '  sectId: bigint("sect_id", { mode: "bigint" }).notNull(),',
  '  discordId: text("discord_id").notNull().unique(),',
  '  name: text("name").notNull(),',
  '  role: text("role").notNull().default("ngoai_mon"), // tong_chu | pho_tong_chu | truong_lao | chap_su | noi_mon | ngoai_mon',
  '  contribution: bigint("contribution", { mode: "bigint" }).notNull().default(0n),',
  '  warPoints: integer("war_points").notNull().default(0),',
  '  joinedAt: timestamp("joined_at").defaultNow().notNull(),',
  '});',
  '',
  '// 3. BẢNG LỊCH SỬ CHIẾN TRANH PK TÔNG MÔN',
  'export const sectWarsTable = pgTable("sect_wars", {',
  '  id: bigint("id", { mode: "bigint" }).primaryKey().generatedAlwaysAsIdentity(),',
  '  attackerSectId: bigint("attacker_sect_id", { mode: "bigint" }).notNull(),',
  '  defenderSectId: bigint("defender_sect_id", { mode: "bigint" }).notNull(),',
  '  status: text("status").notNull().default("active"), // active | attacker_won | defender_won',
  '  attackerDamage: integer("attacker_damage").notNull().default(0),',
  '  defenderDamage: integer("defender_damage").notNull().default(0),',
  '  plunderedStones: bigint("plundered_stones", { mode: "bigint" }).notNull().default(0n),',
  '  pkPointsExchanged: integer("pk_points_exchanged").notNull().default(0),',
  '  startedAt: timestamp("started_at").defaultNow().notNull(),',
  '  endedAt: timestamp("ended_at"),',
  '});',
  '',
  'export const insertSectSchema = createInsertSchema(sectsTable).omit({ id: true, createdAt: true, updatedAt: true });',
  'export const insertSectMemberSchema = createInsertSchema(sectMembersTable).omit({ id: true, joinedAt: true });',
].join('\n');

// File: src/commands/tongmon.ts (Discord.js v14 Slash Command)
export const DISCORD_SLASH_COMMAND_CODE = [
  'import { SlashCommandBuilder, ChatInputCommandInteraction, EmbedBuilder } from "discord.js";',
  'import { db } from "@/lib/db";',
  'import { playersTable } from "@/lib/db/schema/players";',
  'import { sectsTable, sectMembersTable, sectWarsTable } from "@/lib/db/schema/sects";',
  'import { eq, and, desc } from "drizzle-orm";',
  '',
  'const MIN_REALM_FOR_CREATION = "Kim Đan"; // Cảnh giới tối thiểu để lập Tông Môn',
  'const CREATION_COST = 5000n;             // 5,000 Linh Thạch phí lập phái',
  '',
  'export const data = new SlashCommandBuilder()',
  '  .setName("tongmon")',
  '  .setDescription("Hệ thống Tông Môn & PK Tông Môn Chiến")',
  '  .addSubcommand(sub =>',
  '    sub.setName("tao")',
  '      .setDescription("Khai sơn lập phái (Yêu cầu: Kim Đan Kỳ & 5,000 Linh Thạch)")',
  '      .addStringOption(opt => opt.setName("ten").setDescription("Tên Tông Môn").setRequired(true))',
  '      .addStringOption(opt => opt.setName("khauhieu").setDescription("Khẩu hiệu / Tông quy").setRequired(false))',
  '  )',
  '  .addSubcommand(sub =>',
  '    sub.setName("thongtin")',
  '      .setDescription("Xem thông tin chi tiết Tông Môn")',
  '      .addStringOption(opt => opt.setName("ten").setDescription("Tên Tông Môn").setRequired(false))',
  '  )',
  '  .addSubcommand(sub =>',
  '    sub.setName("donggop")',
  '      .setDescription("Đóng góp Linh Thạch vào ngân khố Tông Môn")',
  '      .addIntegerOption(opt => opt.setName("soluong").setDescription("Số lượng Linh Thạch").setRequired(true))',
  '  )',
  '  .addSubcommand(sub =>',
  '    sub.setName("tuyenchien")',
  '      .setDescription("Tuyên chiến Tông Môn khác để phát động PK Tông Môn Chiến")',
  '      .addStringOption(opt => opt.setName("ten_dich").setDescription("Tên Tông Môn muốn PK").setRequired(true))',
  '  )',
  '  .addSubcommand(sub =>',
  '    sub.setName("tapkich")',
  '      .setDescription("Tập kích Hộ Sơn Trận Pháp hoặc đệ tử Tông Môn địch trong chiến tranh")',
  '  )',
  '  .addSubcommand(sub =>',
  '    sub.setName("bxh")',
  '      .setDescription("Bảng xếp hạng Thế Lực & Điểm PK Tông Môn")',
  '  );',
  '',
  'export async function execute(interaction: ChatInputCommandInteraction) {',
  '  const subcommand = interaction.options.getSubcommand();',
  '  const discordId = interaction.user.id;',
  '',
  '  const [player] = await db.select().from(playersTable).where(eq(playersTable.discordId, discordId)).limit(1);',
  '  if (!player) {',
  '    return interaction.reply({ content: "⚠️ Đạo hữu chưa tạo nhân vật tu tiên! Dùng lệnh /tutien batdau trước.", ephemeral: true });',
  '  }',
  '',
  '  // 1. TẠO TÔNG MÔN (Kiểm tra cảnh giới + 5000 Linh Thạch)',
  '  if (subcommand === "tao") {',
  '    const sectName = interaction.options.getString("ten", true).trim();',
  '    const slogan = interaction.options.getString("khauhieu") || "Nhất đạo thông thiên, vạn cổ trường tồn!";',
  '',
  '    const [existingMember] = await db.select().from(sectMembersTable).where(eq(sectMembersTable.discordId, discordId)).limit(1);',
  '    if (existingMember) {',
  '      return interaction.reply({ content: "⚠️ Đạo hữu đã gia nhập Tông Môn khác, không thể khai tông lập phái mới!", ephemeral: true });',
  '    }',
  '',
  '    const REALM_RANKS = ["Phàm Nhân", "Luyện Khí", "Trúc Cơ", "Kim Đan", "Nguyên Anh", "Hóa Thần", "Luyện Hư", "Hợp Thể", "Đại Thừa", "Độ Kiếp"];',
  '    const playerRealmRank = REALM_RANKS.indexOf(player.realm);',
  '    const requiredRealmRank = REALM_RANKS.indexOf(MIN_REALM_FOR_CREATION);',
  '',
  '    if (playerRealmRank < requiredRealmRank) {',
  '      return interaction.reply({',
  '        content: "❌ Tu vi chưa đủ! Cần đạt cảnh giới Kim Đan Kỳ trở lên mới có thể khai sơn lập phái.",',
  '        ephemeral: true',
  '      });',
  '    }',
  '',
  '    if (BigInt(player.spiritStones) < CREATION_COST) {',
  '      return interaction.reply({',
  '        content: "❌ Không đủ Linh Thạch! Cần 5,000 Linh Thạch để xây dựng hộ sơn trận pháp.",',
  '        ephemeral: true',
  '      });',
  '    }',
  '',
  '    // Trừ 5000 linh thạch và tạo Tông Môn',
  '    await db.update(playersTable)',
  '      .set({ spiritStones: BigInt(player.spiritStones) - CREATION_COST })',
  '      .where(eq(playersTable.discordId, discordId));',
  '',
  '    const [newSect] = await db.insert(sectsTable).values({',
  '      name: sectName,',
  '      leaderDiscordId: discordId,',
  '      leaderName: player.name,',
  '      slogan: slogan,',
  '      spiritTreasury: 1000n,',
  '      formationDurability: 5000,',
  '      maxFormationDurability: 5000,',
  '      pkPoints: 1000,',
  '    }).returning();',
  '',
  '    await db.insert(sectMembersTable).values({',
  '      sectId: newSect.id,',
  '      discordId: discordId,',
  '      name: player.name,',
  '      role: "tong_chu",',
  '      contribution: 1000n,',
  '    });',
  '',
  '    const embed = new EmbedBuilder()',
  '      .setColor(0xF59E0B)',
  '      .setTitle("🚩 KHAI TÔNG LẬP PHÁI THÀNH CÔNG: " + sectName)',
  '      .setDescription("Thiên địa linh khí chấn động! Đạo hữu " + player.name + " đã sáng lập Tông Môn!")',
  '      .addFields(',
  '        { name: "👑 Tông Chủ", value: player.name, inline: true },',
  '        { name: "🛡️ Hộ Sơn Trận Pháp", value: "Cấp 1 (5,000 / 5,000 HP)", inline: true },',
  '        { name: "⚔️ Điểm PK Thế Lực", value: "1,000 Điểm", inline: true },',
  '        { name: "📜 Tông Quy", value: slogan }',
  '      );',
  '',
  '    return interaction.reply({ embeds: [embed] });',
  '  }',
  '',
  '  // 2. TUYÊN CHIẾN & PK TÔNG MÔN',
  '  if (subcommand === "tuyenchien") {',
  '    const enemyName = interaction.options.getString("ten_dich", true).trim();',
  '    return interaction.reply("⚔️ Đã gửi chiến thư huyết sát tới Tông Môn " + enemyName + "!");',
  '  }',
  '',
  '  return interaction.reply({ content: "Lệnh hợp lệ.", ephemeral: true });',
  '}',
].join('\n');

export const DISCORD_SLASH_COMMANDS_CODE = DISCORD_SLASH_COMMAND_CODE;
